/* soapBasicHttpBinding_USCOREIOGServiceProxy.h
   Generated by gSOAP 2.8.36 for myService.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapBasicHttpBinding_USCOREIOGServiceProxy_H
#define soapBasicHttpBinding_USCOREIOGServiceProxy_H
#include "soapH.h"

    class SOAP_CMAC BasicHttpBinding_USCOREIOGServiceProxy : public soap {
      public:
        /// Endpoint URL of service 'BasicHttpBinding_USCOREIOGServiceProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in myService.h, if any
        /// Construct a proxy with new managing context
        BasicHttpBinding_USCOREIOGServiceProxy();
        /// Copy constructor
        BasicHttpBinding_USCOREIOGServiceProxy(const BasicHttpBinding_USCOREIOGServiceProxy& rhs);
        /// Construct proxy given a managing context
        BasicHttpBinding_USCOREIOGServiceProxy(const struct soap&);
        /// Constructor taking an endpoint URL
        BasicHttpBinding_USCOREIOGServiceProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIOGServiceProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIOGServiceProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIOGServiceProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and managing context
        virtual ~BasicHttpBinding_USCOREIOGServiceProxy();
        /// Initializer used by constructors
        virtual void BasicHttpBinding_USCOREIOGServiceProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual BasicHttpBinding_USCOREIOGServiceProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        BasicHttpBinding_USCOREIOGServiceProxy& operator=(const BasicHttpBinding_USCOREIOGServiceProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetGloves' (returns SOAP_OK or error code)
        virtual int GetGloves(_ns1__GetGloves *ns1__GetGloves, _ns1__GetGlovesResponse &ns1__GetGlovesResponse)
        { return this->GetGloves(NULL, NULL, ns1__GetGloves, ns1__GetGlovesResponse); }
        virtual int GetGloves(const char *soap_endpoint, const char *soap_action, _ns1__GetGloves *ns1__GetGloves, _ns1__GetGlovesResponse &ns1__GetGlovesResponse);
        /// Web service operation 'RefreshGloves' (returns SOAP_OK or error code)
        virtual int RefreshGloves(_ns1__RefreshGloves *ns1__RefreshGloves, _ns1__RefreshGlovesResponse &ns1__RefreshGlovesResponse)
        { return this->RefreshGloves(NULL, NULL, ns1__RefreshGloves, ns1__RefreshGlovesResponse); }
        virtual int RefreshGloves(const char *soap_endpoint, const char *soap_action, _ns1__RefreshGloves *ns1__RefreshGloves, _ns1__RefreshGlovesResponse &ns1__RefreshGlovesResponse);
        /// Web service operation 'SaveGlove' (returns SOAP_OK or error code)
        virtual int SaveGlove(_ns1__SaveGlove *ns1__SaveGlove, _ns1__SaveGloveResponse &ns1__SaveGloveResponse)
        { return this->SaveGlove(NULL, NULL, ns1__SaveGlove, ns1__SaveGloveResponse); }
        virtual int SaveGlove(const char *soap_endpoint, const char *soap_action, _ns1__SaveGlove *ns1__SaveGlove, _ns1__SaveGloveResponse &ns1__SaveGloveResponse);
        /// Web service operation 'Activate' (returns SOAP_OK or error code)
        virtual int Activate(_ns1__Activate *ns1__Activate, _ns1__ActivateResponse &ns1__ActivateResponse)
        { return this->Activate(NULL, NULL, ns1__Activate, ns1__ActivateResponse); }
        virtual int Activate(const char *soap_endpoint, const char *soap_action, _ns1__Activate *ns1__Activate, _ns1__ActivateResponse &ns1__ActivateResponse);
        /// Web service operation 'Connect' (returns SOAP_OK or error code)
        virtual int Connect(_ns1__Connect *ns1__Connect, _ns1__ConnectResponse &ns1__ConnectResponse)
        { return this->Connect(NULL, NULL, ns1__Connect, ns1__ConnectResponse); }
        virtual int Connect(const char *soap_endpoint, const char *soap_action, _ns1__Connect *ns1__Connect, _ns1__ConnectResponse &ns1__ConnectResponse);
        /// Web service operation 'Disconnect' (returns SOAP_OK or error code)
        virtual int Disconnect(_ns1__Disconnect *ns1__Disconnect, _ns1__DisconnectResponse &ns1__DisconnectResponse)
        { return this->Disconnect(NULL, NULL, ns1__Disconnect, ns1__DisconnectResponse); }
        virtual int Disconnect(const char *soap_endpoint, const char *soap_action, _ns1__Disconnect *ns1__Disconnect, _ns1__DisconnectResponse &ns1__DisconnectResponse);
    };
#endif
