/* soapBasicHttpBinding_USCOREIOGServiceProxy.cpp
   Generated by gSOAP 2.8.36 for myService.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapBasicHttpBinding_USCOREIOGServiceProxy.h"

BasicHttpBinding_USCOREIOGServiceProxy::BasicHttpBinding_USCOREIOGServiceProxy() : soap(SOAP_IO_DEFAULT)
{	BasicHttpBinding_USCOREIOGServiceProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

BasicHttpBinding_USCOREIOGServiceProxy::BasicHttpBinding_USCOREIOGServiceProxy(const BasicHttpBinding_USCOREIOGServiceProxy& rhs)
{	soap_copy_context(this, &rhs);
	this->soap_endpoint = rhs.soap_endpoint;
}

BasicHttpBinding_USCOREIOGServiceProxy::BasicHttpBinding_USCOREIOGServiceProxy(const struct soap &_soap) : soap(_soap)
{ }

BasicHttpBinding_USCOREIOGServiceProxy::BasicHttpBinding_USCOREIOGServiceProxy(const char *endpoint) : soap(SOAP_IO_DEFAULT)
{	BasicHttpBinding_USCOREIOGServiceProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = endpoint;
}

BasicHttpBinding_USCOREIOGServiceProxy::BasicHttpBinding_USCOREIOGServiceProxy(soap_mode iomode) : soap(iomode)
{	BasicHttpBinding_USCOREIOGServiceProxy_init(iomode, iomode);
}

BasicHttpBinding_USCOREIOGServiceProxy::BasicHttpBinding_USCOREIOGServiceProxy(const char *endpoint, soap_mode iomode) : soap(iomode)
{	BasicHttpBinding_USCOREIOGServiceProxy_init(iomode, iomode);
	soap_endpoint = endpoint;
}

BasicHttpBinding_USCOREIOGServiceProxy::BasicHttpBinding_USCOREIOGServiceProxy(soap_mode imode, soap_mode omode) : soap(imode, omode)
{	BasicHttpBinding_USCOREIOGServiceProxy_init(imode, omode);
}

BasicHttpBinding_USCOREIOGServiceProxy::~BasicHttpBinding_USCOREIOGServiceProxy()
{
	this->destroy();
	}

void BasicHttpBinding_USCOREIOGServiceProxy::BasicHttpBinding_USCOREIOGServiceProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        {"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
        {"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
        {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
        {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
        {"ns3", "http://schemas.microsoft.com/2003/10/Serialization/", NULL, NULL},
        {"ns4", "http://schemas.datacontract.org/2004/07/OpenGloveWCF", NULL, NULL},
        {"ns5", "http://schemas.microsoft.com/2003/10/Serialization/Arrays", NULL, NULL},
        {"ns1", "http://tempuri.org/", NULL, NULL},
        {NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this, namespaces);
}

#ifndef WITH_PURE_VIRTUAL
BasicHttpBinding_USCOREIOGServiceProxy *BasicHttpBinding_USCOREIOGServiceProxy::copy()
{	BasicHttpBinding_USCOREIOGServiceProxy *dup = SOAP_NEW_COPY(BasicHttpBinding_USCOREIOGServiceProxy(*(struct soap*)this));
	return dup;
}
#endif

BasicHttpBinding_USCOREIOGServiceProxy& BasicHttpBinding_USCOREIOGServiceProxy::operator=(const BasicHttpBinding_USCOREIOGServiceProxy& rhs)
{	soap_copy_context(this, &rhs);
	this->soap_endpoint = rhs.soap_endpoint;
	return *this;
}

void BasicHttpBinding_USCOREIOGServiceProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void BasicHttpBinding_USCOREIOGServiceProxy::reset()
{	this->destroy();
	soap_done(this);
	soap_initialize(this);
	BasicHttpBinding_USCOREIOGServiceProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void BasicHttpBinding_USCOREIOGServiceProxy::soap_noheader()
{	this->header = NULL;
}

::SOAP_ENV__Header *BasicHttpBinding_USCOREIOGServiceProxy::soap_header()
{	return this->header;
}

::SOAP_ENV__Fault *BasicHttpBinding_USCOREIOGServiceProxy::soap_fault()
{	return this->fault;
}

const char *BasicHttpBinding_USCOREIOGServiceProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *BasicHttpBinding_USCOREIOGServiceProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int BasicHttpBinding_USCOREIOGServiceProxy::soap_close_socket()
{	return soap_closesock(this);
}

int BasicHttpBinding_USCOREIOGServiceProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void BasicHttpBinding_USCOREIOGServiceProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void BasicHttpBinding_USCOREIOGServiceProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *BasicHttpBinding_USCOREIOGServiceProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int BasicHttpBinding_USCOREIOGServiceProxy::GetGloves(const char *endpoint, const char *soap_action, _ns1__GetGloves *ns1__GetGloves, _ns1__GetGlovesResponse &ns1__GetGlovesResponse)
{	struct soap *soap = this;
	struct __ns1__GetGloves soap_tmp___ns1__GetGloves;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8733/Design_Time_Addresses/OpenGloveWCF/OGService/";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/IOGService/GetGloves";
	soap_tmp___ns1__GetGloves.ns1__GetGloves = ns1__GetGloves;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetGloves(soap, &soap_tmp___ns1__GetGloves);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetGloves(soap, &soap_tmp___ns1__GetGloves, "-ns1:GetGloves", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetGloves(soap, &soap_tmp___ns1__GetGloves, "-ns1:GetGloves", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__GetGlovesResponse*>(&ns1__GetGlovesResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__GetGlovesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetGlovesResponse.soap_get(soap, "ns1:GetGlovesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREIOGServiceProxy::RefreshGloves(const char *endpoint, const char *soap_action, _ns1__RefreshGloves *ns1__RefreshGloves, _ns1__RefreshGlovesResponse &ns1__RefreshGlovesResponse)
{	struct soap *soap = this;
	struct __ns1__RefreshGloves soap_tmp___ns1__RefreshGloves;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8733/Design_Time_Addresses/OpenGloveWCF/OGService/";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/IOGService/RefreshGloves";
	soap_tmp___ns1__RefreshGloves.ns1__RefreshGloves = ns1__RefreshGloves;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__RefreshGloves(soap, &soap_tmp___ns1__RefreshGloves);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__RefreshGloves(soap, &soap_tmp___ns1__RefreshGloves, "-ns1:RefreshGloves", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__RefreshGloves(soap, &soap_tmp___ns1__RefreshGloves, "-ns1:RefreshGloves", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__RefreshGlovesResponse*>(&ns1__RefreshGlovesResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__RefreshGlovesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__RefreshGlovesResponse.soap_get(soap, "ns1:RefreshGlovesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREIOGServiceProxy::SaveGlove(const char *endpoint, const char *soap_action, _ns1__SaveGlove *ns1__SaveGlove, _ns1__SaveGloveResponse &ns1__SaveGloveResponse)
{	struct soap *soap = this;
	struct __ns1__SaveGlove soap_tmp___ns1__SaveGlove;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8733/Design_Time_Addresses/OpenGloveWCF/OGService/";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/IOGService/SaveGlove";
	soap_tmp___ns1__SaveGlove.ns1__SaveGlove = ns1__SaveGlove;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__SaveGlove(soap, &soap_tmp___ns1__SaveGlove);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SaveGlove(soap, &soap_tmp___ns1__SaveGlove, "-ns1:SaveGlove", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SaveGlove(soap, &soap_tmp___ns1__SaveGlove, "-ns1:SaveGlove", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__SaveGloveResponse*>(&ns1__SaveGloveResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__SaveGloveResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SaveGloveResponse.soap_get(soap, "ns1:SaveGloveResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREIOGServiceProxy::Activate(const char *endpoint, const char *soap_action, _ns1__Activate *ns1__Activate, _ns1__ActivateResponse &ns1__ActivateResponse)
{	struct soap *soap = this;
	struct __ns1__Activate soap_tmp___ns1__Activate;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8733/Design_Time_Addresses/OpenGloveWCF/OGService/";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/IOGService/Activate";
	soap_tmp___ns1__Activate.ns1__Activate = ns1__Activate;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__Activate(soap, &soap_tmp___ns1__Activate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Activate(soap, &soap_tmp___ns1__Activate, "-ns1:Activate", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Activate(soap, &soap_tmp___ns1__Activate, "-ns1:Activate", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__ActivateResponse*>(&ns1__ActivateResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__ActivateResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ActivateResponse.soap_get(soap, "ns1:ActivateResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREIOGServiceProxy::Connect(const char *endpoint, const char *soap_action, _ns1__Connect *ns1__Connect, _ns1__ConnectResponse &ns1__ConnectResponse)
{	struct soap *soap = this;
	struct __ns1__Connect soap_tmp___ns1__Connect;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8733/Design_Time_Addresses/OpenGloveWCF/OGService/";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/IOGService/Connect";
	soap_tmp___ns1__Connect.ns1__Connect = ns1__Connect;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__Connect(soap, &soap_tmp___ns1__Connect);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Connect(soap, &soap_tmp___ns1__Connect, "-ns1:Connect", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Connect(soap, &soap_tmp___ns1__Connect, "-ns1:Connect", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__ConnectResponse*>(&ns1__ConnectResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__ConnectResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ConnectResponse.soap_get(soap, "ns1:ConnectResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int BasicHttpBinding_USCOREIOGServiceProxy::Disconnect(const char *endpoint, const char *soap_action, _ns1__Disconnect *ns1__Disconnect, _ns1__DisconnectResponse &ns1__DisconnectResponse)
{	struct soap *soap = this;
	struct __ns1__Disconnect soap_tmp___ns1__Disconnect;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8733/Design_Time_Addresses/OpenGloveWCF/OGService/";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/IOGService/Disconnect";
	soap_tmp___ns1__Disconnect.ns1__Disconnect = ns1__Disconnect;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__Disconnect(soap, &soap_tmp___ns1__Disconnect);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Disconnect(soap, &soap_tmp___ns1__Disconnect, "-ns1:Disconnect", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Disconnect(soap, &soap_tmp___ns1__Disconnect, "-ns1:Disconnect", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__DisconnectResponse*>(&ns1__DisconnectResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__DisconnectResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__DisconnectResponse.soap_get(soap, "ns1:DisconnectResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
